[package]
name = "trashy-xml"
version = "0.2.2"
authors = ["Andreas Strømberg<andreas.stromberg90@gmail.com>"]
description = "Less than stellar xml parser, but does what I need in a \"simple\" way"
edition = "2018"

documentation = "https://docs.rs/trashy-xml"
repository = "https://github.com/Stromberg90/trashy-xml"

readme = "README.md"
keywords = ["xml", "parser"]
categories = ["parsing", "text-processing"]
license = "MIT"

[dependencies]
proptest = "0.9.5"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "benchmarks"
harness = false